export const MAX_FADE_IN_DELAY = 0.75
export const ANIMATION_DURATION = 0.5
export const ANIMATION_EASE = "power2.inOut"

export const SHORT_DEBOUNCE_MS = 100
export const LONG_DEBOUNCE_MS = 250

export const DEBOUNCE_TRANSITION = `opacity ${LONG_DEBOUNCE_MS / 1000}s ease-in-out`
export const MOBILE_BREAKPOINT = 768
export const LARGE_DESKTOP_BREAKPOINT = 1920
export const EXTRA_LARGE_DESKTOP_BREAKPOINT = 2560

export const ALL_PROJECTS_MIN_GAP = 40
export const ALL_PROJECTS_MAX_GAP = 55
export const ALL_PROJECTS_MAX_GAP_RAMP = 15

export const ALL_PROJECTS_ROW_HEIGHT = 100
export const ALL_PROJECTS_ROW_HEIGHT_RAMP = 75

export const ALL_PROJECTS_X_MARGIN = 30

export const SELECTED_WORKS_INFINITE_SCROLL_COPY_COUNT = 45
export const SELECTED_WORKS_SNAP_STRICTNESS = "mandatory"
export const SELECTED_WORKS_SNAP_STOP = "normal"

export const SELECTED_WORKS_RECENTER_MIN_MULTIPLES = 5
export const SELECTED_WORKS_EDGE_CUSHION_MULTIPLES = 3
export const SELECTED_WORKS_SCROLL_THRESHOLD = 5
export const SELECTED_WORKS_REQUIRES_SOFT_ADJUSTMENT_THRESHOLD = 4
export const SHOULD_BLEND_THRESHOLD = 20
export const CENTER_ADJUST_DELAY_MS = 200

export const FADE_DURATION_MS = 250